//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Console_GameOfLife.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Files {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Files() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Console_GameOfLife.Resources.Files", typeof(Files).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .o88b.  .d88b.  db       .d88b.  d8888b.
        ///d8P  Y8 .8P  Y8. 88      .8P  Y8. 88  `8D
        ///8P      88    88 88      88    88 88oobY&apos;
        ///8b      88    88 88      88    88 88`8b
        ///Y8b  d8 `8b  d8&apos; 88booo. `8b  d8&apos; 88 `88.
        /// `Y88P&apos;  `Y88P&apos;  Y88888P  `Y88P&apos;  88   YD.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .o88b.  .d88b.  d8b   db d888888b d8888b.  .d88b.  db      .d8888.
        ///d8P  Y8 .8P  Y8. 888o  88 `~~88~~&apos; 88  `8D .8P  Y8. 88      88&apos;  YP
        ///8P      88    88 88V8o 88    88    88oobY&apos; 88    88 88      `8bo.
        ///8b      88    88 88 V8o88    88    88`8b   88    88 88        `Y8b.
        ///Y8b  d8 `8b  d8&apos; 88  V888    88    88 `88. `8b  d8&apos; 88booo. db   8D
        /// `Y88P&apos;  `Y88P&apos;  VP   V8P    YP    88   YD  `Y88P&apos;  Y88888P `8888Y&apos;.
        /// </summary>
        internal static string Controls {
            get {
                return ResourceManager.GetString("Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Daydream {
            get {
                return ResourceManager.GetStream("Daydream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d888b   .d8b.  .88b  d88. d88888b
        ///88&apos; Y8b d8&apos; `8b 88&apos;YbdP`88 88&apos;
        ///88      88ooo88 88  88  88 88ooooo
        ///88  ooo 88~~~88 88  88  88 88~~~~~
        ///88. ~8~ 88   88 88  88  88 88.
        /// Y888P  YP   YP YP  YP  YP Y88888P.
        /// </summary>
        internal static string Intro1 {
            get {
                return ResourceManager.GetString("Intro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .d88b.  d88888b
        ///.8P  Y8. 88&apos;
        ///88    88 88ooo
        ///88    88 88~~~
        ///`8b  d8&apos; 88
        /// `Y88P&apos;  YP.
        /// </summary>
        internal static string Intro2 {
            get {
                return ResourceManager.GetString("Intro2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to db      d888888b d88888b d88888b
        ///88        `88&apos;   88&apos;     88&apos;
        ///88         88    88ooo   88ooooo
        ///88         88    88~~~   88~~~~~
        ///88booo.   .88.   88      88.
        ///Y88888P Y888888P YP      Y88888P.
        /// </summary>
        internal static string Intro3 {
            get {
                return ResourceManager.GetString("Intro3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .88b  d88. d88888b d8b   db db    db
        ///88&apos;YbdP`88 88&apos;     888o  88 88    88
        ///88  88  88 88ooooo 88V8o 88 88    88
        ///88  88  88 88~~~~~ 88 V8o88 88    88
        ///88  88  88 88.     88  V888 88b  d88
        ///YP  YP  YP Y88888P VP   V8P ~Y8888P&apos;.
        /// </summary>
        internal static string MenuBanner {
            get {
                return ResourceManager.GetString("MenuBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d8888b. d8888b. d88888b db    db d888888b d88888b db   d8b   db
        ///88  `8D 88  `8D 88&apos;     88    88   `88&apos;   88&apos;     88   I8I   88
        ///88oodD&apos; 88oobY&apos; 88ooooo Y8    8P    88    88ooooo 88   I8I   88
        ///88~~~   88`8b   88~~~~~ `8b  d8&apos;    88    88~~~~~ Y8   I8I   88
        ///88      88 `88. 88.      `8bd8&apos;    .88.   88.     `8b d8&apos;8b d8&apos;
        ///88      88   YD Y88888P    YP    Y888888P Y88888P  `8b8&apos; `8d8&apos; .
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d8888b. db    db db      d88888b .d8888.
        ///88  `8D 88    88 88      88&apos;     88&apos;  YP
        ///88oobY&apos; 88    88 88      88ooooo `8bo.
        ///88`8b   88    88 88      88~~~~~   `Y8b.
        ///88 `88. 88b  d88 88booo. 88.     db   8D
        ///88   YD ~Y8888P&apos; Y88888P Y88888P `8888Y&apos;.
        /// </summary>
        internal static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .d8888.  .d88b.  d8b   db  d888b  .d8888.
        ///88&apos;  YP .8P  Y8. 888o  88 88&apos; Y8b 88&apos;  YP
        ///`8bo.   88    88 88V8o 88 88      `8bo.
        ///  `Y8b. 88    88 88 V8o88 88  ooo   `Y8b.
        ///db   8D `8b  d8&apos; 88  V888 88. ~8~ db   8D
        ///`8888Y&apos;  `Y88P&apos;  VP   V8P  Y888P  `8888Y&apos;.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Space {
            get {
                return ResourceManager.GetStream("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Viking {
            get {
                return ResourceManager.GetStream("Viking", resourceCulture);
            }
        }
    }
}
